main:
  steps:
    - constants:
        assign:
          - gcs_to_bq_url: https://us-central1-prasad-gcp4-project.cloudfunctions.net/function-1
          
    
    - gcs_to_bq:
        call: http.post
        args:
          url: ${gcs_to_bq_url}
          body:
              message: "Hello world!"
              
        result: some_result
        next: end