name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:
  Cloud_Run_deploy:
    name: Cloud Run Deploy
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: wd
        run: |
          cd cloud-run/my-cloud-run
          pwd

      - name: Build Docker image
        run: docker build ./cloud-run/my-cloud-run --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}

      - name: Deploy Docker image
        run: gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} --region europe-west1  --platform managed --allow-unauthenticated

     