name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:
  Cloud_Run_deploy:
    name: Cloud Run Deploy
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Configure Docker in prod
        run: gcloud auth configure-docker --quiet