# Build cloud run image
# Git Actions -> GCP authentication
# Terraform steps..

name: Build and Deploy to Cloud Run

on:
  pull_request:
    branches:
      - dev
    paths:
      - '.github/workflows/my_cloud_run_deploy_pr.yml'
      - 'cloud-run/my-cloud-run/**'

jobs:
  my_cloud_run_deploy:
    name: Deploy my_cloud_run service
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: wd
        run: |
          cd cloud-run/my-cloud-run
          pwd

      - name: Build Docker image
        run: docker build ./cloud-run/my-cloud-run --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
        run: docker build ./cloud-run/my-cloud-run --tag ${GCP_REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPOSITORY }}/${{ secrets.GCP_APPLICATION }}

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}

      