# Build cloud run image
# reference: https://medium.com/@sbkapelner/building-and-pushing-to-artifact-registry-with-github-actions-7027b3e443c1

name: Build and Deploy to Cloud Run

on:
  pull_request:
    branches:
      - dev
    paths:
      - '.github/workflows/my_cloud_run_deploy_pr.yml'
      - 'cloud-run/my-cloud-run/**'

env:
  TF_WORKING_DIR: infra/my-cloud-run/env
  TF_ENV: dev


jobs:
  build-cloud-run-image:
    name: Build cloud run image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hello-cloud-run
      REPO_NAME: repo-prasad-gcp4
    steps:
      - name: setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: wd
        run: |
          cd cloud-run/my-cloud-run
          pwd

      - name: Build Docker image
        run: docker build  ./cloud-run/my-cloud-run -t $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/$REPO_NAME/$IMAGE_NAME:latest
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/$REPO_NAME/$IMAGE_NAME:latest

  terraform-deploy:
    name: Terraform deployment
    runs-on: ubuntu-latest
    needs: [build-cloud-run-image]
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.3
      
      - name: Terraform version
        id: version
        run: terraform -version

      - name: wd
        run: |
          cd infra/my-cloud-run/env
          pwd
      
      - name: Terraform Init
        id: init
        run: |-
          terraform \
          init \
          -backend-config="$TF_ENV/config.gcs.tfbackend"